USE `osztv_adatbazis`;
START TRANSACTION;

INSERT INTO `FELADAT` (`feladat_id`,`feladat_ev`,`feladat_kerdes`,`feladat_a`,`feladat_b`,`feladat_c`,`feladat_d`,`feladat_e`,`feladat_f`,`feladat_helyes`) VALUES
(121,2,'Milyen előnye van az e -ink használatának?','az e-ink technológia közel 16.7 millió szín megjelenítését teszi lehetővé.','az e-ink kijelzőknek nagyon magas a képfrissítési frekvenciája ez ért nem','az e-ink kijelző csak akkor fogyaszt áramot, amikor változik a kép, ezért sokáig','az e-ink kijelző nem vibrál , ezért sokkal kevésbé fárasztja a szemet használat','','','C,D'),
(122,2,'Melyik állítás igaz?','A programok szerzői jogát a törvény nem, csak a BSA védi.','A megvásárolt program egy adásvétel keretében eladható.','A szoftverhez mellékelt dokumentáció nem tartozik a szerzői jog védelme alá.','A freeware és shareware ugyanazt jelenti.','','','B'),
(123,2,'Melyik állítás igaz az M2M technológiára?','Az M2M technológia az emberek közötti biztonságos és titkosított','Az M2M technológia olyan adatáramlást jelent, mely emberi közreműködés','Az M2M technológia a csoportmunka legújabb, egyben legfontosabb','Az M2M technológia minimum 20Gbit/s -os vonalon valósítható csak meg.','','','B'),
(124,2,'Ohm törvényének felhasználásával válassza ki, hogy mennyi lesz az U értéke, ha az R=76Ω és az I=1,2A?','100V','91,2V','63,3V','15,7V','','','B,D'),
(125,2,'Melyik pixelgrafikus fájlformátum az alábbiak közül?','PDF','CDR','BMP','SWF','','','C'),
(126,2,'A felsorolt eszközök közül melyik nem periféria?','Mikrofon','RAM','Játékvezérlő','Hangkártya','','','B'),
(127,2,'Mit jelent az EULA?','elolvasása után lesz jogunk használni egy programot','végfelhasználói licencszerződés','szabad szoftverek használatát szabályozó szerződés','csak az EULA jogköre alá tartozó szoftverek létezhetnek','','','B'),
(128,2,'Mekkora a Class  1 Bluetooth maximális hatótávolsága?','20 m','50 m','10 m','100 m','','','D'),
(129,2,'Az alábbi állítások közül melyik igaz a vírusokra?','Ha a rendszerbe vírus került, semmiképp sem irtható le a merevlemezen lévő','Megfertőzheti a merevlemez boot szektorát, végső soron akár a teljes','A vírusok egy speciális fajtája az elektronikus sugárzáson keresztül is terjed,','A számítógépes vírusok egymásnak is ártanak, ezért egy gépen egyszerre csak','','','A,B,D'),
(130,2,'Melyik parancs segítségével törölhe tő Linuxos rendszeren  egy könyvtárból az összes, csak „archiv” karakterekkel kezdődő állomány? ','rm a*','del archiv*','rm archiv','rm archiv*','','','D'),
(131,2,'Melyik a processzor órajel lehetséges értéke napjainkban asztali számítógépek esetén? ','2,2 kHz','3,2 MHz','4,2 GHz','5,2 THz','','','C'),
(132,2,'Melyik állítás helyes?','A RAM tartalma szabadon módosítható, nem úgy , mint a merevlemezé.','A HDD egy memóriatípust jelent, és a High Density Data storage rövidítése.','Mentéskor az adat háttértárolóra kerül.','Egy BR-ROM meghajtó általában gyorsabb eszköz, mint a merevlemez.','','','C'),
(133,2,'Mely adathordozó nem formázható?','Merevlemez','USB pen drive','SD kártya','DVD -ROM','','','D'),
(134,2,'Hány elsődleges partíció lehet egy háttértáron ?','4','2','6','bármennyi','','','A'),
(135,2,'Hol tárolódik a BIOS -ban beállított adat?','Az operatív tárban.','A BIOS és a CMOS tárolja','Háttértárolón','Az operációs rendszer gondoskodik a backupról.','','','B,D'),
(136,2,'Az alábbi eszközök közül melyikről nem lehet betölteni egy Pc operációs rendszerét?','floppy lemez','CD-ROM','streamer kazetta','pendrive','','','C'),
(137,2,'Egy CAD/CAM munkaállomás kialakításánál mely hardvereszköz kiemelt szerepű az alábbiak közül?','nagy teljesítményű videókártya','csúcsminőségű hangkártya','DisplayPort','fejlett hűtéstechnika','','','A'),
(138,2,'Milyen színrendszert használnak a monitorok?','HSV','RGB','CMYK','CRY','','','B'),
(139,2,'Hány lemez szükséges minimum a RAID 5 megvalósításához ?','2','3','4','5','','','B'),
(140,2,'Melyik a Windows 10 alapértelmezett fájlrendszere?','exFAT','NTFS','FAT32','EXT4','','','B'),
(141,2,'Videokártyacsere esetén mely szempont  a legfo ntosabb ?','a gépbe szerelt RAM  mérete','a gép CPU típusa','a beépített HDD mérete','az alaplapi bővítőhely típusa','','','D'),
(142,2,'Melyik állítás igaz a RAM -ra?','Írható -olvasható.','Csak olvasható.','Soros elérésű.','Olyan memória, amely kikapcsolás után is megőrzi tartalmát.','','','A'),
(143,2,'Az alábbi eszközök közül melyiken szabad töredezettség mentesítést végezni?','HDD','Blu-Ray lemez','SD kártya','SSD meghajtó','','','A'),
(144,2,'Melyik rövidítés port az alábbiak közül?','SCSI','RFI','UTP','UPS','','','A'),
(145,2,'Mi a CACHE funkciója?','Lehetővé teszi a számítógép számára a hálózathoz való csatlakozást.','A játékok és grafikus alkalmazások számára illesztő felületet biztosít.','A számítógép bekapcsolásakor e llenőrzi az összes belső összetevőt.','Ideiglenes adattárolást biztosít a CPU számára.','','','D'),
(146,2,'Egy hálózati kártya MAC címe hexadecimálisan: 01 -40-F4-43-04-F3. Melyik a bináris megfelelője?','0100000011110100010000110000010011110011','000000010100000011110100010000110000010011110011','00100000011110100010000110000010011110011','000100000011110100001000000010100000010011110011','','','B,D'),
(147,2,'Mi okozhatta azt, hogy a lézer  nyomtató „csíkosan” nyomtatott a papírra?','A nyomtatószoftver gazdaságos üzemmódra van állítva.','A nyomtató szalagja elkopott.','A toner ben kevés a festék .','A nyomtatót fotópapír helyett má s típusú papírral töltötték fel.','','','C'),
(148,2,'Milyen színrendszert használnak a nyomtatók ?','HSV','RGB','CMYK','CRY','','','C'),
(149,2,'Melyik állítás igaz a ROM -ra?','Tartalmát a gép kikapcsolásakor is megtartja','Bármelyik része közvetlenül megcímezhető, írható, olvasható','Működése mágneses  technikán alapul','Mérete nagyban befolyásolja a gép sebességét','','','A,D'),
(150,2,'Az alábbiak közül melyek az alkalmazási réteg protokolljai ?','POP3','ICMP','CSMA/CD','SMTP','','','A,D'),
(151,2,'Az alábbiak közül melyik irányító protokoll?','OSF','PIR','EIGRP','SNMP','','','C'),
(152,2,'Mit jelent a CSMA/CD csatornahozzáférési mód esetén a CD kifejezés?','vivőjel érzékelés','ütközés figyelés','ütközés elkerülés','ütközés megelőzés','','','B'),
(153,2,'Melyik TCP/IP modell réteg felel meg az OSI első két rétegének?','Alkalmazási','Hálózatelérési','Szállítási','Internet','','','B'),
(154,2,'Mi történik, ha nem, vagy hibásan adjuk meg az alapértelmezett átjáró címét egy hálózatra kötött gép konfigurálásakor?','A gép a belső hálózat gépeit el fogja érni.','A gép a belső és külső hálózat gépeit is eléri.','A gép csak a külső hálózat gépeit fogja elérni.','A gép semmilyen más géppel nem fog tudni kommunikálni.','','','A,D'),
(155,2,'Mi a hiba a következő IPv6 -címmel: 2001:DB6:85a3::1319:8a2e::7348?','Nem FE80 -al kezdődik.','DB6 helyett 0DB6 -ot kell írni, így nem érvényes a cím.','Két helyen van benne dupla kettőspont.','Mindenhol dupla kettőspontnak kellene szerepelnie.','','','C'),
(156,2,'Mi a neve annak az eljárásnak, amikor belső IP címeket fordítunk át egy külső IP címre, és azzal érik el a belső hálózat gépei a távoli kiszolgálókat? ','NAI','PAI','NAT','ATP','','','C'),
(157,2,'Mi a MAC -cím utolsó 24 bitjének rövidített neve?','OUI','LLC','NIC','MAC','','','C'),
(158,2,'Mi a szórási címe a 180.168.120.100 állomás alhálózatának, ha /2 5-ös az alhálózati maszkja? ','180.168.120.64','180.168.120.95','180.168.120.127','180.168.120.255','','','C'),
(159,2,'Milyen IPv6 -cím a 2001:db8:a0b:12f0::1?','Csoportcím','Egyedi cím','Szórásos cím','Érvénytelen cím','','','B'),
(160,2,'Melyik fogalom kapcsolódik WLAN -ok biztonságához?','WAP','VLAN','WPA 2','VTP','','','C,D'),
(161,2,'A forgalomirányító melyik memóriájában található az indító konfiguráció?','ROM','FLASH','NVRAM','RAM','','','C'),
(162,2,'Mely  alkalmazás - port páros helyes?','ssh – 23','ftp – 21','smtp – 69','https - 433','','','B'),
(163,2,'Hogyan vehetjük rá a kapcsolókat, hogy megtanulják a hozzájuk kapcsolt gépek MAC címét, és csak a megtanult címet fogadják el a későbbiekben?','switchport port -security mac -address sticky','switchport port-security mac -address dc -49-a9-3a-6c-73','switchport port -security','switchport port -secutritiy aging static','','','A'),
(164,2,'Melyik protokoll segítségével juthatnak IP címhez és hálózati információkhoz a hálózati eszközök?','SNMP','IRC','DHCP','IMAP','','','C'),
(165,2,'Mi az , ami az UDP protokollból hiányzik, de a TCP protokollban benne van ?','Hibadetektálás.','Adatkommunikáció kiépítésének képessége.','IP címek használata .','Nyugtázás .','','','C,D'),
(166,2,'Az alábbiak közül a 168.100.100.20/27 -es című állomás melyiknek nem küld közvetlen ARP kérést, ha kommunikálni szeretne vele? ','168.100.100.1 0','168.100.100.40','168.100.100.30','168.100.100.24','','','B'),
(167,2,'Melyik az az üzenet, amelyet akkor küld egy állomás, ha ismert IP -címhez keres MAC -címet? ','ARP','BOOTP','DNS','RARP','','','A'),
(168,2,'Milyen átviteli közeg látható az alábbi képen?','STP kábel','telefon kábel','UTP kábel','Optikai kábel','','','B'),
(169,2,'Mi jellemző a kiterjesztett hozzáférési listákra?','Csak az irányítandó IP csomagok forrás címé t képes ellenőrizni.','Forrás, célcím, protokoll és port egyeztetésére egyaránt képesek.','Célhoz minél közelebbi router/interfészhez célszerű rendelni.','Forráshoz minél közelebbi interfészhez célszerű rendelni.','','','B,D,E'),
(170,2,'Milyen program alkalmas leginkább egy számítógép hálózati adatforgalmának kontrollálására?','Tűzfal','Vírusírtó','Házirend','Reklámblokkoló','','','A'),
(171,2,'Mi okozhatja az interfész következő állapotát?','rossz minőségű kábel','lekapcsolt interfész a kapcsolat túloldalán','eltérő beágyazási mód a kapcsolat két végén','aktív shutdown parancs az interfészen','','','A,B'),
(172,2,'Mi okozhat egy UTP kábelben elektromágneses interferenciát ?','Sok UTP kábel egymás mellett elvezetve.','Nagyfeszültségű vezetékek az UTP kábel közelében.','UTP és STP kábelek egyidejű használata.','Rosszul bekötött csatlakozó a kábel végén.','','','B'),
(173,2,'Melyik fogalomhoz tartozik a következő meghatározás? A támadások egy speciális fajtája, amikor a támadó nem betörni akar, hanem egy adott 
szolgáltatás működését szeretné megbénítani','Denial of Service (DoS)','DNS spoofing','Address spoofing','Portscan','','','A'),
(174,2,'Melyik állítás igaz a Bluetooth technológiára ?','802.11b szabványt használ.','2,5 Ghz -es frekvenciasávban működik.','2,4 Ghz -es frekvenciasávban működik.','Csak hang átvitelére használják.','','','A,B,C,D'),
(175,2,'Milyen alrétegekre lehet osztani az adatkapcsolati réteget?','DAT alréteg','MAC alréteg','LLC alréteg','PHZ alréteg','','','B,C'),
(176,2,'Melyik parancs segítségével hozhat létre egy ’proba’ nevű adatbázist és állíthatja be a karakter kódolást utf8-ra?','CREATE DATABASE proba','ALTER DATABASE proba CHARACTER SET utf8','CREATE DATABASE proba CHARACTER SET utf8','DROP DATABASE proba CHARACTER SET utf8','','','C'),
(177,2,'Melyik parancs segítségével lehet egy adatbázisból névsorban kiíratni a második 10 (11-20) rekord tartalmát?','SELECT * FROM adatok ORDER BY nev LIMIT 10, 10','SELECT * FROM adatok LIMIT 10 ORDER nev','SELECT * FROM adatok ORDER BY nev LIMIT 11, 20','SELECT * FROM adatok LIMIT 11, 20 ORDER BY nev','','','A'),
(178,2,'Melyik parancs segítségével  lehet ki listáz ni „A” és „B” táblából azok at a rekordok at, amik mind a két táblában szerepelnek?','SELECT * FROM A INNER JOIN B ON A .kulcs=B.kulcs','SELECT * FROM A RIGHT JOIN B ON A.kulcs=B.kulcs WHERE A.kulcs IS NULL','SELECT * FROM A FULL OUTER JOIN B ON A.kulcs=B.kulcs WHERE A.kulcs IS','SELECT * FROM A RIGHT JOIN  B ON A.kulcs=B.kulcs WHERE B .kulcs IS NULL','','','A,D'),
(179,2,'Melyik parancs segítségével  lehet ki listáz ni „A” és „B” táblából azokat a rekordokat, amik csak az A vagy csak a B táblában szerepelnek? ','SELECT * FROM A INNER JOIN B ON A.kulcs=B.kulcs','SELECT * FROM A RIGHT JOIN B ON A.kulcs=B.kulcs WHERE A.kulcs IS NULL','SELECT * FROM A FULL OUTER JOIN B ON A.kulcs=B.kulcs WHERE A.kulcs IS','SELECT * FROM A RIGHT JOIN  B ON A.kulcs=B.kulcs WHERE B .kulcs IS NULL','','','C'),
(180,2,'Adott a következő tábla: CAR  (rend_sz , marka , tipus , szin, kivitel , evjarat , listaar) Melyik SQL parancs kérdezi le a 2023 előtti évjáratú autók márkáját és típusát?','SELECT marka, tipus  WHERE evjarat <2023 FROM car;','SELECT * FROM car WHERE evjarat <2023;','SELECT marka, tipus FROM car WHERE evjarat<20 23;','SELECT marka, evjarat  FROM car WHERE evjarat >2023;','','','C'),
(181,2,'A fejlesztői csapat egy közös projekten dolgozik. Az elkészült kód központi repository -ja a https://github.com/user/project címen érhető el. Három branch van, beton, fejleszt 
és kiadas néven. Jelölje be az alábbiak közül az igaz állításokat! ','A repository helyi másolatát a git copy https://github.com/user/project  paranccsal lehet','A kiadas branchre a git checkout kiadas paranccsal lehet átváltani.','A git commit paranccsal lehet a helyi változásokat a központi repositoryba feltölteni.','A git pull  paranccsal lehet a központi repositoryban levő változásokat letölteni.','','','B,D'),
(182,2,'Adott a következő tábla: CAR  (rend_sz , marka , tipus , szin, kivitel , evjarat , listaar) Mi a hatása a következő SQL utasításnak?
DELETE FROM car WHERE evjarat BETWEEN 2020 AND 2022;','Törli a car tábla összes adatát.','Törli az evjarat mezőben lévő azon adatokat, amelyek 20 20 és 20 22 közé esnek.','Törli azon autók összes adatát, amelyeket 2020 és 2022  között  gyártottak.','Törli azon autók  összes adatát, amelyeket 20 20-ban vagy 20 22-ben gyártottak .','','','C,D'),
(183,2,'Adott a következő tábla: CAR  (rend_sz , marka , tipus , szin, kivitel , evjarat , listaar) Melyik SQL parancs ad hozzá egy teljesitmeny nevű mezőt a táblához? ','ADD TABLE car IN teljesitmeny  INT;','CREATE TABLE car ADD teljesitmeny  INT;','ALTER TABLE car ADD teljesitmeny  INT;','UPDATE TABLE car ADD teljesitmeny  INT;','','','C'),
(184,2,'Adott a következő tábla: CAR  (rend_sz , marka , tipus , szin, kivitel , evjarat , listaar) Melyik SQL parancs segítségével tudja kilistázni azon autók adatait, amik többe
kerülnek, mint a Mazda MX5-ös model?','SELECT * FROM car WHERE listaar>Mazda.MX5.listaar ;','SELECT * FROM car WHERE car.listaar>(SELECT * FROM car  WHERE','SELECT * FROM car WHERE car.listaar>(SELECT listaar FROM car WHERE','SELECT * FROM car WHERE listaar>(SELECT marka=’Mazda’ AND tipus=’MX5’) ;','','','C'),
(185,2,'Mit eredményez a következő SQL utasítás?','Megmutatja az iskolák átlagos pontszámait','Kikeresi azokat a tanulókat, akiknek a pontja 80 fölött van, és megadja az iskolájukat.','Kiírja azon iskolák számát, ahol az átlagos pontszám 80 felett volt.','Kikeresi azokat az iskolákat, ahol az átlagos pontszám 80 pont fölött van, és megadja','','','D'),
(186,2,'Adott a következő tábla: BOOK (konyv_ID, szerzo, cim, kategoria, kiado, kiadev, ar) Melyik SQL parancs növeli az összes könyv árát 20%-al?','UPDATE book SET ar=ar+20;','UPDATE book SET ar=ar*1.2;','ALTER TABLE book SET ar=ar*1.2','UPDATE book SET ar=ar*1.8 WHERE ar<5000;','','','B,D'),
(187,2,'Melyik algoritmus -leíró eszköz látható az alábbi ábrán?','folyamatábra','struktogram','Jackson -diagram','blokkdiagram','','','A'),
(188,2,'Melyik vezérlési szerkezet általános alakja a következő? do{ciklusmag utasításai;}while (feltétel) ','kétirányú elágazás','növekményes ciklus','hátultesztelős ciklus','elöltesztelős ciklus','','','C'),
(189,2,'Mit valósít meg a következő algoritmus?','Minimum -kiválasztásos rendezés','Közvetlen kiválasztásos rendezés','Buborékos rendezés','Beillesztéses rendezés','','','B,D'),
(190,2,'Melyik kifejezés igaz az alábbiak közül?','10101101 B < 172 D','145 D > 90 H','10111111 B = BE H','149 D>10010111 B','','','B'),
(191,2,'Mi lesz a decimális eredmény, ha bitenkénti  AND műveletet végzünk 8 biten a következő két számon?','28','30','31','60','','','A'),
(192,2,'Az alábbiak közül mely adattípusok szolgálnak egész számok tárolására?  ','char','short','long','float','','','B,C'),
(193,2,'Melyik feltételt kell használnunk akkor, ha azt szeretnénk vizsgálni, hogy az adott évszám szökőév-e és egyben századforduló is?','evszam % 4 != 0','evszam % 100 != 0','evszam % 4 != 0 && evszam % 100 != 0','evszam % 4 == 0 && evszam % 100 == 0','evszam % 4 == 0','evszam % 100 == 0','C'),
(194,2,'Mely  kifejezések igazak az alábbiak közül? ','10111001 B < 180 D','145 D > 8FH','10111111 B = BA H','150D<10010111 B','','','B,D'),
(195,2,'Melyik adattípus biztosítja a leggazdaságosabb tárhelyfoglalást, ha egy tornász pontszámait szeretnénk eltárolni (a pontozó bírák által adható maximális pontszám 
10, és tizedes értékeket is adhatnak pl.: 8,6)?','short','float','double','decimal','','','B'),
(196,2,'Melyik adatmodell esetén alkalmazható az SQL nyelv?','hierarchikus','hálós','relációs','EER','','','C'),
(197,2,'Melyik fogalomhoz tartozik a következő meghatározás?','Konstruktor','Destruktor','Metódus','Mutató','','','D'),
(198,2,'OOP (objektumorientált programozás) esetén melyik az a hozzáférési (láthatósági) szint, amelyben az adott taghoz csak az adott osztály és leszármazottjai férhetnek 
hozzá? ','public','protected','internal','private','','','B'),
(199,2,'Mi nem igaz az algoritmusra?','A feladat megoldásában mind a lépések számának, mind az egyes lépéseknek végesnek','Minden lépésnek egyértelműnek kell lennie, hogy ne lehessen félreérteni.','Fontos, hogy minden lépés elvégezhető legyen.','Csak valamilyen algoritmus leíró nyelven készülhet.','','','D'),
(200,2,'Melyik nem része egy algoritmusnak?','Szekvencia','Specifikáció','Szelekció','Iteráció','','','B'),
(201,2,'Melyik kifejezés hiányzik a mondatból? Objektumorientált programozás esetén a ______________ felelős az objektum által 
használt erőforrások felszabadításáért.','konstruktor','destruktor','metódus','virtuális metódus','','','B'),
(202,2,'Mit csinál az alábbi programkód?','Kiírja 12 osztóit a képernyőre, kivéve a 12-öt, vesszővel elválasztva.','Kiírja a 12 osztóit a képernyőre vesszővel elválasztva.','Kiírja a 12 prímosztóit a képernyőre vesszővel elválasztva.','Kiírja a számokat 1 -től 12 -ig a képernyőre vesszővel elválasztva.','','','B,D'),
(203,2,'Mi kerül a képernyőre az alábbi program futásának eredményeként?','4','16','24','32','','','C'),
(204,2,'Melyik HTML utasítással jelezhetjük egy felsorolás elemeit ?','<dl>','<li>','<il>','<list>','','','B'),
(205,2,'Melyik HTML utasítás eredményez működő hiperhivatkozást?','<a href ="http://www.parlament.hu">Országgyűlés</a>','<a name="http://www.parlament.hu">Országgyűlés</a>','<a>http://www.parlament.hu</a>','<a url="http://www.parlament.hu">Országgyűlés</a>','','','A'),
(206,2,'Az alábbiak közül melyik határoz meg jelölőnégyzet típusú űrlap mezőt?','<input type="check" name=" auto" value="1">','<form type="checkbox" name=" auto" value="1">','<input type="checkbox" name=" auto" value="1">','<input type="checkname=" auto" value="1">','','','C'),
(207,2,'Milyen tag -et kell használni a weboldalak táblázataiban a táblázat egy -egy cellájának meghatározására? ','<cell>','<td>','<tr>','<table>','','','B,D'),
(208,2,'Melyik megoldással léphetünk vissza az előző oldalra egy weblapon ?','<a href= ”history.back() ”>Vissza</a>','<a href=”history.go( -1)”>Vissza</a>','<a href=”javascript:history.back()”>Vissza</a>','<a href=”javascript.history.go( -1)”>Vissza</a>','','','C'),
(209,2,'Hogyan hozható létre egy weboldalon belül a „fejezet1” nevű könyvjelzőre mutató hivatkozás?','<a name="#fejezet1">Első fejezet</a>','<a id="fejezet1">Első fejezet</a>','<a href="#fejezet1">Első fejezet</a>','<a href="fejezet1.html">Első fejezet</a>','','','C'),
(210,2,'HTML -ben melyik határoz meg egyszerű (egysoros) szöveges beviteli mezőt?','<text name="cím" value="">','<select type="text" name="cím" value="">','<option type="text" name="cím" value="">','<input type="text" name="cím" value="">','','','D'),
(211,2,'Hogyan adható meg a HTML táblázatokban a keret vastagsága?','a <table> "line" jellemzőjével','a <table> "border" jellemzőjével','a <table> "margin" jellemzőjével','a <table> "width" jellemzőjével','','','B'),
(212,2,'Mire szolgál a HTML űrlapoknál az <input type=" button "> tag?','Szöveges beviteli mező elhelyezésére.','"Űrlap elküldése" gomb elhelyezésére.','Nyomógomb  elhelyezésére.','Az űrlap aláírására.','','','C'),
(213,2,'Melyik HTML utasítással csatolhatjuk a külső CSS fájlt a weblaphoz?','<stylesheet>  rel=" stylesheet" mystyle.css  type="text/css" </stylesheet>','<link rel="stylesheet" type="text/css" href="mystyle.css">','<style src="mystyle.css"  rel="stylesheet"  type="text/css" >','<a href="mystyle.css"  rel="stylesheet"  type="text/css" ></a>','','','B,D'),
(214,2,'Hogyan épül fel általánosan egy CSS utasítás?','kijelölö{tulajdonság1:ertek1;tulajdonsag2:ertek2;}','kijelölö{tulajdonság1,tulajdonsag2:ertek1,ertek2;}','#tulajdonság{kijelölö: ertek1:ertek2;}','.tulajdonság{kijelölö: ertek1:ertek2;}','','','A'),
(215,2,'Melyik CSS utasítás igazítja balra  a picture azonosítójú képet?','.picture{text -align: left}','#picture{float: left}','#picture{text -align: left}','.picture{float: left}','','','B'),
(216,2,'Melyik CSS utasítással készíthetünk egy olyan „side”  azonosítójú szelektort, amely a magasságot 500, a szélességet 80 képpontosra állítja? ','#side{height:80px;width:5 00px}','.side{height:5 00px;width:80px}','#side{height:5 00px;width:80px}','.side{height:80px;width:5 00px}','','','C'),
(217,2,'Mit eredményez  a következő CSS utasítás: h2 { text-decoration :underline ;}','A címsort h2 -re állítja.','Hibás utasítás.','A h2 címsor t színesre állítja .','A h2 címsort aláhúzottra  állítja.','','','D'),
(218,2,'Melyik CS S utasítással állíthatjuk a weboldal  „menü” elemének  betűtípusát Arialra?','body {text -style:Arial;}','text {font -family:Arial;}','menu  {font -family:Arial;}','body {text -family:Arial;}','','','C'),
(219,2,'Mit végez el a következő CSS utasítás? #kép {width:200px;}','Az összes kép szélességét 200 pontosra állítja.','A kép osztályú elem szélességét 200 pontosra állítja.','A kép azonosítójú elem szélességét 200 pontosra állítja.','Ez egy hibás utasítás.','','','C,D'),
(220,2,'CSS-ben keretet szeretne készíteni a következő keretvastagságokkal: Felső keret = 10 képpont, alsó keret = 5 képpont, bal oldali keret = 20 képpont, jobb oldali 
keret = 1 képpont.
Melyik a helyes parancs erre a célra?','border -width:10px 20px 5px 1px;','border -width:10px 1px 5px 20px;','border -width:10px 5px 20px 1px;','d border -width:5px 20px 10px 1px;','','','B'),
(221,2,'Melyik CSS utasítás szünteti meg a hiperhivatkozások aláhúzását?','a {text -decoration:none;}','a {underline:none;}','a {text -decoration:no -underline;}','{decoration:no -underline;}','','','A'),
(222,2,'Melyik JavaScript kód változtatja meg az alábbi „proba ” azonosítójú bekezdésben megjelenő szöveget?','document.getElement("p").innerHTML = "Jó napot!";','#proba.innerHTML = "Jó napot!";','document.getElementByName("p").innerHTML = "Jó napot!";','document.getElementById("proba").innerHTML = "Jó napot!";','','','D'),
(223,2,'Hogyan épül fel a számlálós ciklus ciklusfeje JavaScriptben?','for i in range( 1,5)','for i range( 0;5)','for (i = 0; i <= 5; i++)','for (i <= 5; i++)','','','C,D'),
(224,2,'Hogyan helyezhető el többsoros megjegyzés python  kódban?','//Ez egy','/*Ez egy','<!--Ez egy','”””','','','D'),
(225,2,'Az alábbiak közül melyik hoz létre 3 elemű tömböt JavaScriptben?','var colors = 1 = ("red"), 2 = ("green"), 3 = ("blue")','var colors = (1:"red", 2:"green", 3:"blue")','var colors = {"red", "green", "blue" }','var colors = ["red", "green", "blue"]','','','D'),
(226,2,'Hogyan írhatjuk egy figyelmeztető ablakba a "Hello" szöveget JavaScriptben?','msg("Hello");','alertBox("Hello");','alert("Hello");','msgBox("Hello");','','','C'),
(227,2,'Melyik HTML elembe kell elhelyezni a JavaScript kódot?','<javascript>','<script>','<scripting>','<js>','','','B'),
(228,2,'JavaSriptben melyik metódussal csonkolható  egy tört  szám egészre ?','Math. pow()','round ()','Math.floor( )','Math.round( )','','','C,D'),
(229,2,'Mi lesz az x változó értéke a következő PHP kód lefutása után?','1','5','10','15','','','A'),
(230,2,'Mi lesz az x változó értéke a következő PHP kód lefutása után?','2','4','8','16','','','B'),
(231,2,'PHP programnyelvben melyik utasítással nyi tható meg a jelszo.txt fájl  olvasásra  és írásra?','open("jelszo.txt");','fopen("jelszo.txt","r");','fopen("jelszo.txt","r+");','open ("jelszo.txt","rw ");','','','C,D'),
(232,2,'Mely állítások igazak az objektumorientált programozással (OOP) kapcsolatban?','A természetes gondolkodást, cselekvést közelítő programozási mód.','Csak vizuális programozási nyelven készíthetünk OOP programot.','A vizuális programozási nyelvben készített programok mindig objektumorientáltak.','A mezők az adott osztály alapján létrehozott objektumpéldányok között nem kerülnek','','','A,D,E'),
(233,2,'Mekorra lesz az x változó értéke a következő Java kód lefutása után?','1','4','8','24','','','C,D'),
(234,2,'Melyik rendezési algoritmust valósítja meg a következő Java kód?','Minimum -kiválasztásos rendezés','Közvetlen kiválasztásos rendezés','Buborékos rendezés','Beillesztéses rendezés','','','A'),
(235,2,'A szoftverfejlesztés melyik szakaszában definiálják a szoftver funkcióit, illetve annak megszorításait?','Szoftverspecifikáció','Szoftvertervezés és implementáció','Szoftvervalidáció','Szoftverevolúció','','','A'),
(236,2,'Mely állítások igazak a szoftverfejlesztés során alkalmazott vízesésmodellre?','Alapja az iteráció, melynek segítségével eltérő szakaszokban ugyanazon fejlesztési','Alapvető elgondolása, hogy az ügyfél által a tervezési fázisban felállított','Egyszerű és könnyen menedzselhető felépítése miatt a kisebb és jól definiált','A fejlesztést több részfolyamatra bontják és minden fázist az előző jóváhagyása és','','','C,D,E'),
(237,2,'Határozza meg az  alábbi algoritmus eredményét!','N=2 X=9 K=4','N=4 X=10 K=3','N=6 X=5 K=1','N=7 X=10 K=3','','','B'),
(238,2,'Mennyi lesz x és y értéke az alábbi programrészlet lefutásakor?','x=0 és y=3','x=3 és y=3','x=2 és y=3','x=3 és y=1','','','C,D'),
(239,2,'Mi kerül a képernyőre az alábbi program futásának eredményeként ?','3','7','5','8','','','D'),
(240,2,'Milyen értéket ad vissza az alábbi függvény X = 2023 esetén?','1','3','20','202','','','B,D'),
(241,2,'Milyen értéket ad vissza az alábbi függvény N = 12 esetén?','1','3','20','100','','','A'),
(242,2,'Milyen tag -et kell használni a weboldalak táblázataiban a táblázat egy -egy fejléc cellájának meghatározására?','<cell>','<td>','<head>','<th>','','','D'),
(243,2,'Az alábbiak közül melyik nem része egy HTML oldal szerkezetének?','header','body','caption','head','','','C'),
(244,2,'Az alábbiak közül melyik nem része a HTML5 szemantikus szerkezetének?','header','main','nav','table','','','D,E'),
(245,2,'Mi lesz az eredménye a css opacity:0. 3; utasításnak , ha egy képre alkalmazzák?','semmi','a kép 30% ban  átlátszó lesz','a kép fele részben átlátszó lesz','a kép 70% ban átlátszó lesz','','','D'),
(246,2,'Az alábbiak közül melyik paraméter nem használható css -ben a háttér  beállításainak módosítására?','url("img_tree.png ");','no-repeat;','fixed','double','','','D'),
(247,2,'CSS formázással szeretnék az oldalon egy képet középre igazítani  úgy, hogy a környező szövegektől külön sorba kerüljön. Mi kerüljön a display tulajdonság 
paraméterébe?','semmi','inline','block','inline -block','','','C'),
(248,2,'Mire való egy HTML oldalon a meta tagbe elhelyezett viewport tulajdonság beállítása?','nincs hatása a megjelenítésre','segítségével az eszköz méretéhez igazíthatjuk a tartalmak méretét','beállíthatjuk vele az oldalak legfelső szintjét','különféle nézőpontokat definiálhatunk vele','','','B'),
(249,2,'Az alábbi CSS méret meghatározó mértékegységek közül melyik függ a megjelenítő eszköz dpi felbontásától?','cm','px','pt','mm','','','B,D'),
(250,2,'Az alábbiak közül melyik CSS szelektorral lehet hivatkozni az összes  olyan bekezdésre, amik a div elemen belül helyezkednek el?','div, p','div p','div>p','div+p','','','B'),
(251,2,'Mi az a Bootstrap?','BIOS beállítás , amivel meg lehet határozni a gép indításáért felelős eszközt','JS és CSS keretrendszer','Egy Boot manager program','Statikus weblapok készítéséhez használt segédprogram','','','B');

COMMIT;