USE `osztv_adatbazis`;
START TRANSACTION;

-- Feladatok import
INSERT INTO `feladat` (`feladat_id`, `feladat_ev`, `feladat_kerdes`, `feladat_a`, `feladat_b`, `feladat_c`, `feladat_d`, `feladat_e`, `feladat_f`) VALUES
(121, 3, 'A nagyfelbontású monitor azt jelenti, hogy…', 'a monitor sok színt tud kezelni.', 'a monitor képfrissítése: 120 Hz, vagy több.', 'a monitor képpontjainak száma vertikálisan és horizontálisan is nagy.', 'a monitor képátlója 22”, vagy anná l nagyobb.', '', ''),
(122, 3, 'Melyik állítás igaz?', 'A programok szerzői jogát a törvény nem, csak a BSA védi.', 'A megvásárolt program egy adásvétel keretében eladható.', 'A szoftverhez mellékelt dokumentáció nem tartozik a szerzői jog védelme alá.', 'A freeware és s hareware ugyanazt jelenti.', '', ''),
(123, 3, 'Melyik állítás igaz az M2M technológiára?', 'Az M2M technológi a az emberek közötti biztonságos és titkosított kommunikációt valósítja meg.', 'Az M2M technológia olyan adatáramlást jelent, mely emberi közreműködés nélkül, gépek között zajlik.', 'Az M2M technológia a csoportmunka legújabb, egyben legfontosabb kommunikációs eszköze.', 'Az M2M technológia minimum 20Gbit/s -os vonalon valósítható csak meg.', '', ''),
(124, 3, 'Ohm törvényének felhasználásával válassza ki, hogy mennyi lesz az U értéke, ha az R=76Ω és az I=1,2A?', '100V', '91,2V', '63,3V', '15,7V', '', ''),
(125, 3, 'Melyik pixelgrafikus fájlformátum az alábbiak közül?', 'PDF', 'CDR', 'BMP', 'SWF', '', ''),
(126, 3, 'A felsorolt eszközök közül melyik nem periféria?', 'Mikrofon', 'CPU (Central Processing Unit)', 'Játékvezérlő', 'Hangkártya', '', ''),
(127, 3, 'Mit jelent az EULA?', 'elolvasása után lesz jogunk használni egy programot', 'végfelhasználói licencszerződés', 'szabad szoftverek használatát szabályozó szerződés', 'csak az EULA jogköre alá tartozó szoftverek létezhetnek', '', ''),
(128, 3, 'Mekkora a Class 1 Bluetooth maximális hatótávolsága?', '20 m', '50 m', '10 m', '100 m', '', ''),
(129, 3, 'Az alábbi állítások közül melyik igaz a vírusokra?', 'Ha a rendszerbe vírus került, semmiképp sem irthat ó le a merevlemezen lévő vírusirtóval. Ki kell venni a rendszerlemezt és másik gépbe helyezni a sikeres írtáshoz .', 'Megfertőzheti a merevlemez boot szektorát, végső soron akár a teljes merevlemez tartalma elveszhet.', 'A vírusok egy speciális fajtája az elektro nikus sugárzáson keresztül is terjed, így egy kis irodában lévő minden számítógép gyorsan megfertőződhet.', 'A számítógépes vírusok egymásnak is ártanak, ezért egy gépen egyszerre csak egy vírus lehet jelen.', '', ''),
(130, 3, 'Melyik parancs segítségével törölhe tő Linuxos ren dszeren egy könyvtárból az összes , csak „archiv ” karakterekkel kezdődő állomány ?', 'rm a*', 'del archiv*', 'rm archiv', 'rm archiv*', '', ''),
(131, 3, 'Melyik a processzor órajel lehetséges értéke napjainkban asztali számítógépek esetén?', '2,2 kHz', '3,2 MHz', '4,2 GHz', '5,2 THz', '', ''),
(132, 3, 'Melyik állítás helyes?', 'A RAM tartalma szabadon módosítható, nem úgy, mint a merevlemezé.', 'A HDD egy memóriatípust jelent, és a High Density Data storage rövidítése.', 'Mentéskor az adat háttértárolóra kerül.', 'Egy BR-ROM meghajtó általában gyorsabb eszköz, mint a merevlemez.', '', ''),
(133, 3, 'Mely adathordozó nem formázható?', 'Merevlemez', 'USB pen drive', 'SD kártya', 'DVD -ROM', '', ''),
(134, 3, 'Melyik állítás helyes?', 'Az operációs rendszer egy interfész, ami a hardver és a felhasználó közötti kapcsolatot biztosítja.', 'Az operációs rendszer a gép bekapcsolásakor automatikusan a ROM -ba töltődik.', 'Egy operációs rendszernek nincs hardverigénye, bármilyen konfiguráción működnie kell.', 'Az operációs rendszer verziója, fajtája nem befol yásolja a már megvásárolt programjaink futtathatóságát. (Minden operációs rendszeren minden legális program fut)', '', ''),
(135, 3, 'Jelölje az igaz állítást!', 'A biztonsági másolatot csak a rendszergazda készíthet a gépünk állományairól .', 'Az operációs rendszerek általában támogatják a biztonsági másolatok készítését.', 'Hardverhiba nem okozhat adatvesztést, így a biztonsági másolatok elsősorban a véletlen törlések és a vírusok ellen védenek.', 'Biztonsági másolat csak cserélhető adathordozóra készít hető.', '', ''),
(136, 3, 'Az alábbi eszközök közül melyikről nem lehet betölteni egy P C operációs rendszerét?', 'floppy lemez', 'CD-ROM', 'streamer kazetta', 'pendrive', '', ''),
(137, 3, 'Egy CAD/CAM munkaállomás kia lakításánál mely hardvereszköz kiemelt szerepű az alábbiak közül?', 'nagy teljesítményű videókártya', 'csúcsminőségű hangkártya', 'DisplayPort', 'fejlett hűtéstechnika', 'HDMI/DVI kimenet', ''),
(138, 3, 'Milyen színrendszert használnak a monitorok?', 'HSV', 'RGB', 'CMYK', 'CRY', '', ''),
(139, 3, 'Mi a funkciója az eseménynaplónak?', 'A felhasználok neveit és jelszavait tárolja.', 'A felhasználók kedvenc weboldalait tárolja.', 'A vírusdefiníciós adatbázist tárolja.', 'A gép hardveres és szoftveres változásainak nyomon követését segíti elő.', '', ''),
(140, 3, 'Melyik a Windows 10 alapértelmezett fájlrendszere?', 'exFAT', 'NTFS', 'FAT32', 'EXT4', '', ''),
(141, 3, 'Videokártyacsere esetén mely szempont a legfo ntosabb ?', 'a gépbe szerelt RAM mérete', 'a gép CPU típusa', 'a beépített HDD mérete', 'az alaplapi bővítőhely típusa', '', ''),
(142, 3, 'Melyik állítás igaz a RAM -ra?', 'Írható -olvasható.', 'Csak olvasható.', 'Soros elérésű.', 'Olyan memória, amely kikapcsolás után is megőrzi tartalmát.', '', ''),
(143, 3, 'Az alábbi eszközök közül melyiken szabad töredezettség mentesítést végezni?', 'HDD', 'Blu-Ray lemez', 'SD kártya', 'SSD meghajtó', '', ''),
(144, 3, 'Melyik rövidítés port az alábbiak közül?', 'SCSI', 'RFI', 'UTP', 'UPS', '', ''),
(145, 3, 'Egy videokártyán 600x400 képpont felbontásban 2 szín használható (fekete és fehér). Mekkora memóriára van szük ség ennek megjelenítéséhez?', '240 000 Bájt', '30 000 Bájt', '0,24 Mbájt', '0,3 MBájt', '', ''),
(146, 3, 'Mi a CACHE funkciója?', 'Lehetővé teszi a számítógép számára a hálózathoz való csatlakozást.', 'A játékok és grafikus alkalmazások számára illesztő felületet biztosít.', 'A számítógép bekapcsolásakor e llenőrzi az összes belső összetevőt.', 'Ideiglenes adattárolást biztosít a CPU számára.', '', ''),
(147, 3, 'Egy hálózati kártya MAC címe hexadecimálisan: 01 -40-F4-43-04-F3. Melyik a bináris megfelelője? ... pont / 2 po nt a) 0100000011110100010000110000010011110011 b) 000000010100000011110100010000110000010011110011 c) 00100000011110100010000110000010011110011 d) 000100000011110100001000000010100000010011110011 28. Mi okozhatta azt, hogy a lézer nyomtató „csíkosan” nyomtatott a papírra?', 'A nyomtatószoftver gazdaságos üzemmódra van állítva.', 'A nyomtató szalagja elkopott.', 'A toner ben kevés a festék .', 'A nyomtatót fotópapír helyett más típusú papírral töltötték fel.', '', ''),
(148, 3, 'Milyen színrendszert használnak a nyomtatók ? ... pon t / 2 pont a) HSV b) RGB c) CMYK d) CRY 30. Melyik állítás igaz a ROM ra?', 'Tartalmát a gép kikapcsolásakor is megtartja', 'Bármelyik része közvetlenül megcímezhető, írható, olvasható', 'Működése mágneses technikán alapul', 'Mérete nagyban befolyásolja a gép sebességét', '', ''),
(149, 3, 'Az alábbiak közül melyek az alkalmazási réteg protokolljai? (2 jó válasz)', 'POP3', 'ICMP', 'CSMA/CD', 'SMTP', 'TCP', ''),
(150, 3, 'Az alábbiak közül melyik irányító protokoll?', 'OSF', 'PIR', 'EIGRP', 'SNMP', '', ''),
(151, 3, 'Mit jelent a CSMA/CD csatornahozzáférési mód esetén a CD kifejezés?', 'vivőjel érzékelés', 'ütközés figyelés', 'ütközés elkerülés', 'ütközés megelőzés', '', ''),
(152, 3, 'Melyik TCP/IP modell réteg felel meg az OSI első két rétegének?', 'Alkalmazási', 'Hálózatelérési', 'Szállítási', 'Internet', '', ''),
(153, 3, 'Melyik IP -cím osztályba tartozik a 10.90.118.10 cím?', 'A', 'B', 'C', 'D', '', ''),
(154, 3, 'Mi a hiba a következő IPv6 -címmel: 2001:DB6:85a3::1319:8a2e::7348?', 'Nem FE80 -al kezdődik.', 'DB6 helyett 0DB6 -ot kell írni, így nem érvényes a cím.', 'Két helyen van benne dupla kettőspont.', 'Mindenhol dupla kettőspontnak kellene szerepelnie.', '', ''),
(155, 3, 'Melyik alhálózati maszkk al egyezik meg a /1 9 alakú maszk?', '255.255.128 .0', '255.255.192 .0', '255.255.224.0', '255.255.240.0', '', ''),
(156, 3, 'Mi a MAC -cím utolsó 24 bitjének rövidített neve?', 'OUI', 'LLC', 'NICS', 'MAC', '', ''),
(157, 3, 'Mi a szórási címe a 180.168.120.100 állomás alhálózatának, ha /2 5-ös az alhálózati maszkja?', '180.168.120.64', '180.168.120.95', '180.168.120.127', '180.168.120.255', '', ''),
(158, 3, 'Milyen IPv6 -cím a 2001:db8:a0b:12f0::1?', 'Csoportcím', 'Egyedi cím', 'Szórásos cím', 'Érvénytelen cím', '', ''),
(159, 3, 'Melyik fogalom kapcsolódik WLAN -ok biztonságához?', 'WAP', 'VLAN', 'WPA 2', 'VTP', '', ''),
(160, 3, 'A forgalomirányító melyik memóriájában található az indító konfiguráció?', 'ROM', 'FLASH', 'NVRAM', 'RAM', '', ''),
(161, 3, 'Mely alkalmazás - port páros ok helyes es? (2 jó válasz)', 'ssh – 23', 'ftp – 21', 'smtp – 69', 'https - 443', '', ''),
(162, 3, 'Melyik protokoll segítségével juthatnak IP címhez és hálózati információkhoz a hálózati eszközök ?', 'SNMP', 'IRC', 'DHCP', 'IMAP', '', ''),
(163, 3, 'Hány host kaphat IP címet összesen a 10.200.54.0/24 -es hálózatban?', '126', '128', '256', '254', '', ''),
(164, 3, 'Az alábbiak közül a 168.100.100.20/27 -es című állomás melyiknek nem küld közvetlen ARP kérést, ha kommunikálni szeretne vele?', '168.100.100.1 0', '168.100.100.40', '168.100.100.30', '168.100.100.24', '', ''),
(165, 3, 'Melyik az az üzenet, amelyet akkor küld egy állomás, ha ismert IP -címhez keres MAC - címet?', 'ARP', 'BOOTP', 'DNS', 'RARP', '', ''),
(166, 3, 'Milyen átviteli közeg látható az alábbi képen?', 'STP kábel', 'UTP kábel', 'Koax kábel', 'Optikai kábel', '', ''),
(167, 3, 'Mi jellemző a kiterjesztett hozzáférési listákra? (2 jó válasz)', 'Csak az irányítandó IP csomagok forrás címé t képes ellenőrizni.', 'Forrás, célcím, protokoll és port egyeztetésére egyaránt képesek.', 'Célhoz minél közelebbi router/interfészhez célszerű rendelni.', 'Forráshoz minél közelebbi interfészhez célszerű rendelni.', 'Csak nevesített módon használhatóak.', ''),
(168, 3, 'Melyik az a PDU, amelyik az OSI modell 3. rétegében működik?', 'csomag', 'szegmens', 'keret', 'bitfolyam', '', ''),
(169, 3, 'Mi okozhatja az interfész következő állapotát? (2 jó válasz)', 'rossz minőségű kábel', 'lekapcsolt interfész a kapcsolat túloldalán', 'eltérő beágyazási mód a kapcsolat két végén', 'aktív shutdown parancs az interfészen', '', ''),
(170, 3, 'Melyik az a címzési mód, amely létezik az IPv6 -ban, de az IPv4 -ban nem?', 'Unicast', 'Anycast', 'Multicast', 'Broadcast', '', ''),
(171, 3, 'Melyik fogalomhoz tartozik a következő meghatározás?', 'Denial of Service (DoS)', 'DNS spoofing', 'Address spoofin g', 'Portscan', '', ''),
(172, 3, 'Melyik parancs jeleníti meg a routeren a RAM -ban tárol t aktív konfigurációt?', 'show active -config', 'show config', 'show running -config', 'show startup -config', '', ''),
(173, 3, 'Milyen alrétegekre lehet osztani az adatkapcsolati réteget? (2 jó válasz)', 'DAT alréteg', 'MAC alréteg', 'LLC alréteg', 'PHZ alréteg', '', ''),
(174, 3, 'Adott a következő tábla: CAR (rend_sz , marka , tipus , szin, kivitel , evjarat , listaar) Melyik SQL parancs kérdezi le a 2000 előtt i évjáratú autók márkáját és típusát ?', 'SELECT marka, tipus WHERE evjarat <2000 FROM car;', 'SELECT * FROM car WHERE evjarat <2000;', 'SELECT marka, tipus FROM car WHERE evjarat <2000;', 'SELECT marka, evjarat FROM car WHERE evjarat >2000;', '', ''),
(175, 3, 'A fejlesztői csapat egy közös projekten dolgozik. Az elkészült kód központi repository - ja a https://github.com/user/project címen érhető el. Három branch van, beton, fejleszt és kiadas néven. Jelölje be az alábbiak közül az igaz állításokat! (2 jó válasz)', 'A repository helyi másolatát a git copy https://github.com/user/project paranccsal lehet elkészíteni', 'A kiadas branchre a git checkout kiadas paranccsal lehet átváltani.', 'A git commit paranccsal lehet a helyi változásokat a központi repositoryba feltölteni.', 'A git pull paranccsal lehet a közpon ti repositoryban levő változásokat letölteni.', '', ''),
(176, 3, 'Adott a következő tábla: CAR (rend_sz , marka , tipus , szin, kivitel , evjarat , listaar) Mi a hatása a következő SQL utasításnak? DELETE FROM car WHERE evjarat BETWEEN 2020 AND 20 22;', 'Törli a car tábla összes adatát.', 'Törli az evjarat mezőben lévő azon adatokat, amelyek 20 20 és 20 22 közé esnek.', 'Törli azon autók összes adatát, amelyeket 20 20 és 20 22 gyártottak .', 'Törli azon autók összes adatát, amelyeket 20 20-ban vagy 20 22-ben gyártottak .', '', ''),
(177, 3, 'Adott a következő tábla: CAR (rend_sz , marka , tipus , szin, kivitel , evjarat , listaar) Melyik SQL parancs ad hozzá egy kobcenti nevű mezőt a táblához?', 'ADD TABLE car IN kobcenti INT;', 'CREATE TABLE car ADD kobcenti INT;', 'ALTER TABLE car ADD kobcenti INT;', 'UPDATE TABLE car ADD kobcenti INT;', '', ''),
(178, 3, 'Hogyan kérdezhetőek le az autók nettó árai, ha a táblában csak a bruttó árakat és ÁFA % -os értékét (pl.:25) tároljuk? (A nettó ár az ÁFÁ -val csökkentett ár)', 'SELECT brut to_ar -AFA AS nettó FROM autok;', 'SELECT brutto_ar -brutto_ar*AFA AS nettó FROM autok;', 'SELECT brutto_ar -brutto_ar*AFA/100 AS nettó FROM autok;', 'UPDATE berek SET brutto_ar -bruttó_ar*AFA/100 AS nettó;', '', ''),
(179, 3, 'Mit eredményez a következő SQL utasítás?', 'Megmutatja az iskolák átlagos pontszámait .', 'Kikeresi azokat a tanulókat, akiknek a pontja 80 fölött van, és megadja az iskolájukat.', 'Kiírja azon iskolák számát, ahol az átlagos pontszám 80 felett volt.', 'Kikeresi azokat az iskolákat, ahol az átlagos pontszám 80 pont fölött van, és megadja az átlagos pontszámukat.', '', ''),
(180, 3, 'Adott a következő tábla: BOOK (konyv_ID, szerzo, cim, kategoria, kiado, kiadev, ar) Melyik SQL parancs növeli az összes könyv árát 20% -al?', 'UPDATE book SET ar=ar+20;', 'UPDATE book SET ar=ar*1.2;', 'ALTER TABLE book SET ar=ar*1.2', 'UPDATE book SET ar=ar*1.8 WHERE ar<5000;', '', ''),
(181, 3, 'Melyik algoritmus -leíró eszköz látható az alábbi ábrán?', 'folyamatábra', 'struktogram', 'Jackson -diagram', 'blokkdiagram', '', ''),
(182, 3, 'Melyik vezérlési szerkezet általános alakja a következő?', 'kétirányú elágazás', 'növekményes ciklus', 'hátultesztelős ciklus', 'elöltesztelős ciklus', '', ''),
(183, 3, 'Mit valósít meg a következő algoritmus?', 'Minimum -kiválasztásos rendezés', 'Közvetlen kiválasztásos rendezés', 'Buborékos rendezés', 'Beillesztéses rendezés', '', ''),
(184, 3, 'Melyik kifejezés igaz az alábbiak közül?', '10101101 B < 172 D', '145 D > 90 H', '10111111 B = BE H', '149 D>10010111 B', '', ''),
(185, 3, 'Mi lesz a decimális eredmény, ha bitenkénti AND műveletet végzünk 8 biten a következő két számon?', '28', '30', '31', '60', '', ''),
(186, 3, 'Az alábbiak közül mely adattípusok szolgálnak egész számok tárolására? (2 jó válasz)', 'char', 'short', 'long', 'float', 'double', ''),
(187, 3, 'Melyik feltételt kell használnunk akkor, ha azt szeretnénk vizsgálni, hogy az adott évszám szökőév -e és egyben szá zadforduló is ?', 'evszam % 4 != 0', '', 'evszam % 100 != 0', 'evszam % 4 != 0 && evszam % 100 != 0', 'evszam % 4 == 0 && evszam % 100 == 0', 'evszam % 4 == 0'),
(188, 3, 'Mely kifejezések igazak az alábbiak közül? (2 jó válasz)', '10111001 B < 180 D', '145 D > 90 H', '10111111 B = BA H', '148 D<10010111 B', '', ''),
(189, 3, 'Mit csinál az alábbi programkód?', 'Kiírja 12 osztóit a képernyőre, kivéve a 24-et, vesszővel elválasztva.', 'Kiírja a 12 osztóit a képernyőre vesszővel elválasztva.', 'Kiírja a 12 prímosztóit a képernyőre vesszővel elválasztva.', 'Kiírja a számokat 1 -től 12 -ig a képernyőre vesszővel elválasztva.', '', ''),
(190, 3, 'Melyik adattípus biztosítja a leggazdaságos abb tárhelyfoglalást, ha egy tornász pontszámait szeretnénk eltárolni (a pontozó bírák által adható maximá lis pontszám 10, és tizedes értékeket is adhatnak pl.: 8,6 )?', 'short', 'float', 'double', 'decimal', '', ''),
(191, 3, 'Melyik adatmodell esetén alkalmazható az SQL nyelv?', 'hierarchikus', 'hálós', 'relációs', 'EER', '', ''),
(192, 3, 'Melyik fogalomhoz tartozik a következő meghatározás?', 'Konstruktor', 'Destruktor', 'Metódus', 'Mutató', '', ''),
(193, 3, 'Melyik HTML utasítással jelezhetjük egy felsorolás elemeit?', '<dl>', '<li>', '<il>', '<list>', '', ''),
(194, 3, 'Melyik HTML utasítás eredményez működő hiperhivatkozást?', '<a href="http://www.parlament.hu">Országgyűlés</a>', '<a name="http://www.parlament.hu">Országgyűlés</a>', '<a>http://www.parlament.hu</a>', '<a url="http://www.parlament.hu">Országgyűlés</a>', '', ''),
(195, 3, 'Az alábbiak közül melyik határoz meg jelölőnégyzet típusú űrlap mezőt?', '<input type="check" name="foci" value="1">', '<form type="checkbox" name="foci" value="1">', '<input type="checkbox" name="foci" value="1">', '<input type="checkname="foci" value="1">', '', ''),
(196, 3, 'Milyen tag -et kell használni a weboldalak táblázataiban a táblázat egy -egy cellájának meghatározására?', '<cell>', '<td>', '<tr>', '<table>', '', ''),
(197, 3, 'Melyik tag szolgál egy weboldalon képek beillesztésére?', '<picture src="...">', '<href img src="…">', '<img href="…">', '<img src="…">', '', ''),
(198, 3, 'Hogyan hozható létre egy weboldalon belül a „fejezet1” nevű könyvjelzőre mutató hivatkozás?', '<a name="#fejezet1">Első fejezet</a>', '<a id="fejezet1">Első fejezet</a>', '<a href="#fejezet1">Első fejezet</a>', '<a href="fejezet1.html">Első fejezet</a>', '', ''),
(199, 3, 'HTML -ben melyik határoz meg egyszerű (egysoros) szöveges beviteli mezőt?', '<text name="cím" value="">', '<select type="text" name="cím" value="">', '<option type="text" name="cím" value="">', '<input type="text" name="cím" value="">', '', ''),
(200, 3, 'Hogyan adható meg a HTML táblázatokban a keret vastagsága?', 'a <table> "line" jellemzőjével', 'a <table> "border" jellemzőjével', 'a <table> "margin" jellemzőjével', 'a <table> "width" jellemzőjével', '', ''),
(201, 3, 'Mire szolgál a HTML űrlapoknál az <input type="submit"> tag?', 'Szöveges beviteli mező elhelyezésére.', '"Űrlap elküldése" gomb elhelyezésére.', 'Nyomógomb elhelyezésére .', 'Az űrlap aláírására.', '', ''),
(202, 3, 'Melyik HTML utasítással csatolhatjuk a külső CSS fájlt a weblaphoz?', '<stylesheet> rel="stylesheet" mystyle.css type="text/css" </stylesheet>', '<link rel="stylesheet" type="text/css" href="mystyle.css">', '<style src="mystyle.css" rel="stylesheet" type="te xt/css" >', '<a href="mystyle.css" rel="stylesheet" type="text/css" ></a>', '', ''),
(203, 3, 'Hogyan épül fel általánosan egy CSS utasítás?', 'kijelölö{tulajdonság1:ertek1;tulajdonsag2:ertek2;}', 'kijelölö{tulajdonság1,tulajdonsag2:ertek1,ertek2;}', '#tulajdonság{kijelölö: ertek1:ertek2;}', '.tulajdonság{kijelölö: ertek1:ertek2;}', '', ''),
(204, 3, 'Melyik CSS utasítás igazítja jobbra a picture azonosítójú képet?', '.picture{text -align:right}', '#picture{float:right}', '#picture{text -align:right}', '.picture{float:righ t}', '', ''),
(205, 3, 'Melyik CSS utasítással készíthetünk egy olyan fejléckép azonosítójú szelektort, amely a magasságot 50, a szélességet 800 képpontosra állítja?', '#fejléckép{height:800px;width:50px}', '.fejléckép{height:50px;width:800px}', '#fejléckép{height:50 px;width:800px}', '.fejléckép{height:800px;width:50px}', '', ''),
(206, 3, 'Mit eredményez a következő CSS utasítás: h2 {font -style: italic;}', 'A címsort h2 -re állítja.', 'Hibás utasítás.', 'A h2 címsor nyelvét olaszra állítja.', 'A h2 címsort dőltre állítja.', '', ''),
(207, 3, 'Melyik CSS utasítással állíthatjuk a teljes weboldal betűtípusát Arial -ra?', 'body {text -style:Arial;}', 'text {font -family:Arial;}', 'body {font -family:Arial;}', 'body {text -family:Arial;}', '', ''),
(208, 3, 'Mit végez el a következő CSS utasítás? #kép {width:200px;}', 'Az összes kép szélességét 200 pontosra állítja.', 'A kép osztályú elem szélességét 200 pontosra állítja.', 'A kép azonosítójú elem szélességét 200 pontosra állítja.', 'Ez egy hibás utasítá s.', '', ''),
(209, 3, 'CSS-ben keretet szeretne készíteni a következő keretvastagságokkal: Felső keret = 10 képpont, alsó keret = 5 képpont, bal oldali keret = 20 képpont, jobb oldali keret = 1 képpont. Melyik a helyes parancs erre a célra?', 'border -width:10px 20px 5px 1px;', 'border -width:10px 1px 5px 20px;', 'border -width:10px 5px 20px 1px;', 'd border -width:5px 20px 10px 1px;', '', ''),
(210, 3, 'Melyik CSS utasítás szünteti meg a hiperhivatkozások aláhúzását?', 'a {text -decoration:none;}', 'a {underline:none ;}', 'a {text -decoration:no -underline;}', '{decoration:no -underline;}', '', ''),
(211, 3, 'Melyik JavaScript kód változtatja meg az alábbi proba azonosítójú bekezdésben megjelenő szöveget? <p id="proba">Jó reggelt!</p>', 'document.getElement("p").innerHTML = "Jó napo t!";', '#proba.innerHTML = "Jó napot!";', 'document.getElementByName("p").innerHTML = "Jó napot!";', 'document.getElementById("proba").innerHTML = "Jó napot!";', '', ''),
(212, 3, 'Hogyan épül fel a számlálós ciklus ciklusfeje JavaScriptben?', 'for i in range( 1,5)', 'for i range( 0;5)', 'for (i = 0; i <= 5; i++)', 'for (i <= 5; i++)', '', ''),
(213, 3, 'Hogyan helyezhető el többsoros megjegyzés JavaScript kódban?', '//Ez egy többsoros megjegyzés//', '/*Ez egy többsoros megjegyzés*/', '<!--Ez egy többsoros megjegyzés -->', '//Ez egy //többsoros megjegyzés', '', ''),
(214, 3, 'Az alábbiak közül melyik hoz létre 3 ele mű tömböt JavaScriptben?', 'var colors = 1 = ("red"), 2 = ("green"), 3 = ("blue")', 'var colors = (1:"red", 2:"green", 3:"blue")', 'var colors = {"red", "green", "blue" }', 'var colors = ["red", "green", "blue"]', '', ''),
(215, 3, 'Hogyan írhatjuk egy figyelmeztető ablakba a "Hello" szöveget JavaScriptben?', 'msg("Hello");', 'alertBox("Hello");', 'alert("Hello");', 'msgBox("Hello");', '', ''),
(216, 3, 'Melyik HTML elembe kell elhelyezni a JavaScript kódot?', '<javascript>', '<script>', '<scripting>', '<js>', '', ''),
(217, 3, 'JavaSriptben melyik metódussal adható meg két szám (x,y) közül a nagyobb?', 'Math.ceil(x, y)', 'ceil(x, y)', 'Math.max(x, y)', 'top(x, y)', '', ''),
(218, 3, 'Mi lesz az x változó értéke a következő PHP kód lefutása után?', '1', '5', '10', '15', '', ''),
(219, 3, 'Mi lesz az x változó értéke a következő PHP kód lefutása után?', '2', '4', '5', '15', '', ''),
(220, 3, 'PHP programnyelvben melyik utasítással nyitható meg a jelszo.txt fájl csak olvasásra?', 'open("jelszo.txt");', 'fopen("jelszo.txt","r");', 'fopen("jelszo.txt","r+");', 'open("jelszo.txt","read");', '', ''),
(221, 3, 'Melyik kifejezés hiányzik a mondatból?', 'konstruktor', 'destruktor', 'metódus', 'virtuális metódus', '', ''),
(222, 3, 'Mely állítások igazak az objektumorientált programozással (OOP) kapcsolatban? (3 jó válasz)', 'A természetes gondolkodást, cselekvést közelítő programozási mód.', 'Csak vizuális programozási nyelven készíthetünk OOP programot.', 'A vizuális programozási nyelvben készített programok mindig objektumorientáltak.', 'A mezők az adott osztály alapján létrehozott objektumpéldányok között nem kerülnek megosztásra, hanem minden példány külön -külön mezőkészlettel ren delkezik.', 'Az absztrakt osztályok a legtöbb nyelvben nem példányosíthatók. f) Fontos jellemzőjük az öröklés, amely azt jelenti, hogy egy adott tevékenység (metódus) azonosítója közös lehet egy adott objektum hierarchián belül, ugyanakkor a hierarchia minden eg yes objektumában a tevékenységeket végrehajtó metódus implementációja az adott objektumra nézve specifikus lehet.', ''),
(223, 3, 'OOP (objektumorientált programozás) estén melyik az a hozzáférési (láthatósági) szint, amelyben az adott taghoz csak az adott osztály és leszá rmazott jai férhetnek hozzá?', 'public', 'protected', 'internal', 'private', '', ''),
(224, 3, 'Mekorra lesz az x változó értéke a következő Java kód lefutása után?', '1', '4', '8', '24', '', ''),
(225, 3, 'Melyik rendezési algoritmust valósítja meg a következő Java kód?', 'Minimum -kiválasztásos rendezés', 'Közvetlen kiválasztásos rendezés', 'Buborékos rendezés', 'Beillesztéses rendezés', '', ''),
(226, 3, 'A szoftverfejlesztés melyik szakaszában definiálják a szoftver funkcióit, illetve annak megszorításait?', 'Szoftverspecifikáció', 'Szoftvertervezés és implementáció', 'Szoftvervalidáció', 'Szoftverevolúció', '', ''),
(227, 3, 'Mely állítások igazak a szoftverfejlesztés során alkalmazott vízesésmodellre? (2 jó válasz)', 'Alapja az iteráció, melynek segítségével eltérő szakaszokban ugyanazon fejlesztési terület kidolgozását teszi lehetővé a precízebb végeredmény érdekében.', 'Alapvető elgondolása, hogy az ügyfél által a tervezési fázisban felállított követelmények a fejlesztés során megváltozhatnak.', 'Egyszerű és könnyen menedzselhető felépítése miatt a kisebb és jól definiált projektekhez gyakran használják.', 'A fejlesztést több részfolyamatra bontják és minden fázist az előző jóváhagyása és befejezése után indítanak el.', 'Az általános fejlesztési eljárás helyett egy projektre szabható, igények szerint változtatható keretet nyújt.', ''),
(228, 3, 'Határozza meg az alábbi algoritmus eredményét!', 'N=2 X=9 K=4', 'N=4 X=10 K=3', 'N=6 X=5 K=1', 'N=7 X=10 K=3', '', ''),
(229, 3, 'Mennyi lesz x és y értéke az alábbi programrészlet lefutásakor?', 'x=0 és y=3', 'x=3 és y=3', 'x=2 és y=3', 'x=3 és y=1', '', ''),
(230, 3, 'Milyen értéket ad vissza az alábbi függvény X = 2022 esetén?', '1', '3', '20', '202', '', ''),
(231, 3, 'Milyen értéket ad vissza az alábbi függvény N = 12 esetén?', '1', '3', '20', '100', '', ''),
(232, 3, 'Milyen tag -et kell használni a weboldalak táblázataiban a táblázat egy -egy fejléc cellájának meghatározására?', '<cell>', '<td>', '<head>', '<th>', '', ''),
(233, 3, 'Az alábbia k közül melyik nem része egy HTML oldal szerkezet ének?', 'header', 'body', 'caption', 'head', '', ''),
(234, 3, 'Az alábbiak közül melyik nem része a HTML5 szemantikus szerkezetének?', 'header', 'main', 'nav', 'table', 'section', ''),
(235, 3, 'Mi lesz az eredménye a CSS opacity:0.7; utasításnak , ha egy képre alkalmazzák?', 'semmi', 'a kép 30% -ban átlátszó lesz', 'a kép fele részben átlátszó lesz', 'a kép 70% -ban átlátszó lesz', '', ''),
(236, 3, 'Az alábbiak közül melyik paraméter nem használható CSS-ben a háttér beállításainak módosítására?', 'url("img_tree.png ");', 'no-repeat;', 'fixed', 'double', '', ''),
(237, 3, 'CSS formázással szeretnék az oldalon egy képet középre igazítani úgy, hogy a környező szövegektől külön sorba kerüljön. Mi kerüljön a display tulajdonság paraméterébe?', 'none', 'inline', 'block', 'inline -block', '', ''),
(238, 3, 'Mire való egy HTML oldalon a meta tagbe elh elyezett viewport tulajdonság beállítása?', 'nincs hatása a megjelenítésre', 'segítségével az eszköz méretéhez igazíthatjuk a tartalmak méretét', 'beállíthatjuk vele az oldalak legfelső szintjét', 'különféle nézőpontokat definiálhatunk vele', '', ''),
(239, 3, 'Az aláb bi CSS méret meghatározó mértékegységek közül melyik függ a megjelenítő eszköz dpi felbontásától?', 'cm', 'px', 'pt', 'mm', '', ''),
(240, 3, 'Az alábbiak közül melyik CSS szelektorral lehet hivatkozni az összes olyan bekezdésre, am elyek a div elemen belül helyezkednek e l?', 'div, p', 'div p', 'div>p', 'div+p', '', ''),
(241, 3, 'Mi az a Bootstrap?', 'BIOS beállítás , amivel meg lehet határozni a gép indításáért felelős eszközt', 'JS és CSS keretrendszer', 'Egy Boot manager program', 'Statikus weblapok készítéséhez használt segédprogram', '', '');

-- Megoldások import
INSERT INTO `megoldasok` (`feladat_id`, `feladat_ev`, `feladat_helyes`) VALUES
(121, 3, 'C'),
(122, 3, 'B'),
(123, 3, 'B'),
(124, 3, 'B,D'),
(125, 3, 'C'),
(126, 3, 'B'),
(127, 3, 'B'),
(128, 3, 'D'),
(129, 3, 'A,B,D'),
(130, 3, 'D'),
(131, 3, 'C'),
(132, 3, 'C'),
(133, 3, 'D'),
(134, 3, 'A,D'),
(135, 3, 'B'),
(136, 3, 'C'),
(137, 3, 'A'),
(138, 3, 'B'),
(139, 3, 'D'),
(140, 3, 'B'),
(141, 3, 'D'),
(142, 3, 'A'),
(143, 3, 'A'),
(144, 3, 'A'),
(145, 3, 'B,D'),
(146, 3, 'D'),
(147, 3, 'B'),
(148, 3, 'C'),
(149, 3, 'C'),
(150, 3, 'A,D'),
(151, 3, 'A,D'),
(152, 3, 'C'),
(153, 3, 'B'),
(154, 3, 'B'),
(155, 3, 'A,D'),
(156, 3, 'C'),
(157, 3, 'C'),
(158, 3, 'C'),
(159, 3, 'C'),
(160, 3, 'B'),
(161, 3, 'C,D'),
(162, 3, 'C'),
(163, 3, 'B,D'),
(164, 3, 'C'),
(165, 3, 'D'),
(166, 3, 'B,D'),
(167, 3, 'A'),
(168, 3, 'B'),
(169, 3, 'B,D'),
(170, 3, 'A,D'),
(171, 3, 'A,B'),
(172, 3, 'B'),
(173, 3, 'A'),
(174, 3, 'C'),
(175, 3, 'B,C,D'),
(176, 3, 'C'),
(177, 3, 'B,D'),
(178, 3, 'C,D'),
(179, 3, 'C'),
(180, 3, 'C'),
(181, 3, 'D'),
(182, 3, 'B,D'),
(183, 3, 'A'),
(184, 3, 'D'),
(185, 3, 'B,D'),
(186, 3, 'B'),
(187, 3, 'A'),
(188, 3, 'B,C'),
(189, 3, 'C'),
(190, 3, 'B,D'),
(191, 3, 'B'),
(192, 3, 'B'),
(193, 3, 'C'),
(194, 3, 'D'),
(195, 3, 'B'),
(196, 3, 'A'),
(197, 3, 'C'),
(198, 3, 'B'),
(199, 3, 'D'),
(200, 3, 'C'),
(201, 3, 'D'),
(202, 3, 'B'),
(203, 3, 'B'),
(204, 3, 'B'),
(205, 3, 'A,D'),
(206, 3, 'B'),
(207, 3, 'C'),
(208, 3, 'D'),
(209, 3, 'C'),
(210, 3, 'C,D'),
(211, 3, 'B'),
(212, 3, 'A'),
(213, 3, 'D'),
(214, 3, 'C,D'),
(215, 3, 'B'),
(216, 3, 'D'),
(217, 3, 'C'),
(218, 3, 'B'),
(219, 3, 'C,D'),
(220, 3, 'A'),
(221, 3, 'B'),
(222, 3, 'B,D'),
(223, 3, 'B'),
(224, 3, 'A,D,E'),
(225, 3, 'B,D'),
(226, 3, 'C'),
(227, 3, 'C,D'),
(228, 3, 'A'),
(229, 3, 'C,D,E'),
(230, 3, 'B,D'),
(231, 3, 'C'),
(232, 3, 'B,D'),
(233, 3, 'A'),
(234, 3, 'D'),
(235, 3, 'C,D'),
(236, 3, 'D'),
(237, 3, 'B'),
(238, 3, 'D'),
(239, 3, 'C'),
(240, 3, 'B,D'),
(241, 3, 'B');

COMMIT;